name: C/C++ CI

on: 
  push:
    branches: 
      - master

jobs:
  build:

    runs-on: ubuntu-18.04
    
    steps:
    - uses: actions/checkout@v1
    - name: make
      run: make
    - name: make t1
      run: make t1
   
